allowBuilds:
  '@mercuryworkshop/scramjet': false
patchedDependencies:
  '@mercuryworkshop/scramjet-controller@0.0.9': patches/@mercuryworkshop__scramjet-controller@0.0.9.patch
  '@zip.js/zip.js@2.8.26': patches/@zip.js__zip.js@2.8.26.patch
