name: Continuous Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: pnpm

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Zip artifacts
        run: zip -r 0k.zip dist/

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: latest
          name: Continuous Release
          body: |
            This is 0K, commit ${{ github.sha }}.

            0K can be hosted on any static hosting service, from CodeHS and Techsmart, to Google Cloud Storage and S3, Firebase Hosting and Render Static, or even pages.gay and IPFS.
          artifacts: '0k.zip'
          replacesArtifacts: true
